SELECT B.TOTAL_EM_ATRASO AS ATRASO FROM(

SELECT SUM(CASE WHEN  MONTH(DTVENC) = 1 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN  VLRDESDOB
			ELSE 0 END) JANEIRO,
	SUM(CASE WHEN MONTH(DTVENC) = 2 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) FEVEREIRO,
	SUM(CASE WHEN MONTH(DTVENC) = 3 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) MARCO,
	SUM(CASE WHEN MONTH(DTVENC) = 4 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) ABRIL,
	SUM(CASE WHEN MONTH(DTVENC) = 5 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) MAIO,
	SUM(CASE WHEN MONTH(DTVENC) = 6 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) JUNHO,
	SUM(CASE WHEN MONTH(DTVENC) = 7 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) JULHO,
	SUM(CASE WHEN MONTH(DTVENC) = 8 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) AGOSTO,
	SUM(CASE WHEN MONTH(DTVENC) = 9 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) SETEMBRO,
	SUM(CASE WHEN MONTH(DTVENC) = 10 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) OUTUBRO,
	SUM(CASE WHEN MONTH(DTVENC) = 11 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) NOVEMBRO,
	SUM(CASE WHEN MONTH(DTVENC) = 12 AND YEAR(DTVENC) = YEAR(GETDATE()) THEN VLRDESDOB
			ELSE 0 END) DEZEMBRO,
	SUM(CASE WHEN DTVENC < CAST(CAST(YEAR(GETDATE())AS CHAR(4))+ '-01-01' AS DATE) THEN VLRDESDOB ELSE 0 END) AS VALOR_ANTES_PERIODO,
	SUM(CASE WHEN DTVENC BETWEEN CAST(CAST(YEAR(GETDATE())AS CHAR(4))+ '-01-01' AS DATE) AND DATEADD(DAY, DATEDIFF(DAY, 1, GETDATE()), 0) THEN VLRDESDOB ELSE 0 END) AS ATRASO_ONTEM,
	SUM(CASE WHEN DTVENC < DATEADD(DAY, DATEDIFF(DAY, 1, GETDATE()), 1) THEN VLRDESDOB ELSE 0 END) AS TOTAL_EM_ATRASO,
	SUM(CASE WHEN YEAR(DTVENC) = YEAR(GETDATE())  THEN VLRDESDOB ELSE 0 END) AS VALOR_DENTRO_PERIODO,
	SUM(CASE WHEN YEAR(DTVENC) > YEAR(GETDATE()) THEN VLRDESDOB ELSE 0 END) AS VALOR_FORA_PERIODO,
	SUM(VLRDESDOB) AS VALOR_TOTAL
FROM TGFFIN
WHERE DHBAIXA IS NULL
AND CODEMP IN(1,2,3)
and CODNAT  IN (1010200,1010100,5090000)
AND CODTIPOPER IN (1100,1241,1237,1242,1247,1258,1291,1300)
AND PROVISAO = 'N'
AND RECDESP = 1
AND CODTIPTIT IN (4,36)


)B