

SELECT Y.CODBCO, Y.ABREVIATURA, Y.CODCTABCOINT, Y.DESCRICAO, Y.SALDO, Y.ULT_CONCILIACAO FROM(

SELECT X.CODBCO, X.ABREVIATURA,X.CODCTABCOINT,X.DESCRICAO,X.SALDO,X.ULT_CONCILIACAO FROM (
SELECT
  TEMP.CODBCO,
  TEMP.ABREVIATURA,
  TEMP.CODCTABCOINT,
  TEMP.DESCRICAO,
  SUM(TEMP.SALDO) AS SALDO,
  MAX(TEMP.ULT_CONCILIACAO) AS ULT_CONCILIACAO 
/*  TEMP.CODEMP,
  TEMP.CODPARC*/
FROM (SELECT
  BCO.CODBCO,
  rtrim(BCO.ABREVIATURA)+ ' '+CTA.CODCTABCO AS ABREVIATURA,
  CTA.CODCTABCOINT,
  CTA.DESCRICAO,
  (SELECT
    MAX(MBC.DHCONCILIACAO) 
  FROM TGFMBC MBC 
  WHERE DATEADD(DAY, DATEDIFF(DAY, 0, MBC.DHCONCILIACAO), 0)
  <= DATEADD(DAY, DATEDIFF(DAY, 1, GETDATE()), 0)
  AND MBC.CODCTABCOINT = CTA.CODCTABCOINT)
  AS ULT_CONCILIACAO,
  T1.SALDOBCO 
  + ISNULL((SELECT
    SUM(T7.VLRLANC * T7.RECDESP)
  FROM TGFMBC T7
  WHERE T7.CODCTABCOINT = 7 
  AND T7.DTLANC >= cast('01/'+cast(month(getdate()) as char(2))+'/'+cast(year(getdate()) as char(4)) as date) 
  AND T7.DTLANC < cast(cast(day(getdate()) as char(2))+'/'+cast(month(getdate()) as char(2))+'/'+cast(year(getdate()) as char(4)) as date)), 0)
  AS SALDO,
  CTA.CODEMP,
  CTA.CODPARC,
  BCO.NOMEBCO
FROM TGFSBC T1
INNER JOIN TSICTA CTA
  ON T1.CODCTABCOINT = CTA.CODCTABCOINT
INNER JOIN TSIBCO BCO
  ON BCO.CODBCO = CTA.CODBCO
WHERE T1.REFERENCIA = (SELECT
  MAX(T2.REFERENCIA)
FROM TGFSBC T2
WHERE T2.CODCTABCOINT = T1.CODCTABCOINT
AND (CTA.ATIVA = 'S')
--T2.REFERENCIA < '2022-12-15'
AND DATEADD(DAY, DATEDIFF(DAY, 0, T2.REFERENCIA), 0) <= DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0))
AND CTA.ATIVA = 'S'
AND CTA.CLASSE = 'C'
AND CTA.CODEMP IS NOT NULL) TEMP
WHERE 1 = 1
GROUP BY TEMP.CODBCO,
		 TEMP.ABREVIATURA,
         TEMP.CODCTABCOINT,
         TEMP.DESCRICAO,
         TEMP.CODEMP,
         TEMP.CODPARC,
         TEMP.NOMEBCO
) X
WHERE X.CODCTABCOINT =7 


union all


SELECT Z.CODBCO,Z.ABREVIATURA,Z.CODCTABCOINT,Z.DESCRICAO,Z.SALDO,Z.ULT_CONCILIACAO FROM (
SELECT
  TEMP.CODBCO,
  TEMP.ABREVIATURA,
  TEMP.CODCTABCOINT,
  TEMP.DESCRICAO,
  SUM(TEMP.SALDO) AS SALDO,
  MAX(TEMP.ULT_CONCILIACAO) AS ULT_CONCILIACAO 
/*  TEMP.CODEMP,
  TEMP.CODPARC*/
FROM (SELECT
  BCO.CODBCO,
  rtrim(BCO.ABREVIATURA)+ ' '+CTA.CODCTABCO AS ABREVIATURA,
  CTA.CODCTABCOINT,
  CTA.DESCRICAO,
  (SELECT
    MAX(MBC.DHCONCILIACAO) 
  FROM TGFMBC MBC 
  WHERE DATEADD(DAY, DATEDIFF(DAY, 0, MBC.DHCONCILIACAO), 0)
  <= DATEADD(DAY, DATEDIFF(DAY, 1, GETDATE()), 0)
  AND MBC.CODCTABCOINT = CTA.CODCTABCOINT)
  AS ULT_CONCILIACAO,
  T1.SALDOBCO + ISNULL((SELECT
    SUM(T7.VLRLANC * T7.RECDESP)
  FROM TGFMBC T7
  INNER JOIN TSICTA CTA
    ON T7.CODCTABCOINT = CTA.CODCTABCOINT
  WHERE T1.CODCTABCOINT = T7.CODCTABCOINT
  AND T7.DTLANC >= T1.REFERENCIA 
  AND (CTA.ATIVA = 'S')
  AND DATEADD(DAY, DATEDIFF(DAY, 0, T7.DTLANC), 0) <=
  DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0)), 0) AS SALDO,
  CTA.CODEMP,
  CTA.CODPARC,
  BCO.NOMEBCO
FROM TGFSBC T1
INNER JOIN TSICTA CTA
  ON T1.CODCTABCOINT = CTA.CODCTABCOINT
INNER JOIN TSIBCO BCO
  ON BCO.CODBCO = CTA.CODBCO
WHERE T1.REFERENCIA = (SELECT
  MAX(T2.REFERENCIA)
FROM TGFSBC T2
WHERE T2.CODCTABCOINT = T1.CODCTABCOINT
AND (CTA.ATIVA = 'S')
--T2.REFERENCIA < '2022-12-15'
AND DATEADD(DAY, DATEDIFF(DAY, 0, T2.REFERENCIA), 0) < DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0))
AND CTA.ATIVA = 'S'
AND CTA.CLASSE = 'C'
AND CTA.CODEMP IS NOT NULL) TEMP
WHERE 1 = 1
GROUP BY TEMP.CODBCO,
		 TEMP.ABREVIATURA,
         TEMP.CODCTABCOINT,
         TEMP.DESCRICAO,
         TEMP.CODEMP,
         TEMP.CODPARC,
         TEMP.NOMEBCO
) Z
WHERE Z.CODCTABCOINT IN(9,10,11)  

union all

SELECT 422 AS CODBC, 
	'SAFRA 005859471' AS ABREVIATURA, 
	5 AS CODCTABCOINT,
	'SAFRA CD PRINCIPAL' AS DESCRICAO,
	SUM(T3.VLRLANC * T3.RECDESP) as SALDO,
	CAST(max(t3.DHCONCILIACAO) as date) AS ULT_CONCILIACAO 
FROM TGFMBC T3
WHERE T3.CODCTABCOINT =  5  AND T3.CONCILIADO =  'S' AND T3.DHCONCILIACAO  >= '01/01/2022' AND T3.DHCONCILIACAO  < GETDATE()

UNION ALL 

SELECT 422 AS CODBC,
 'SAFRA 005859463' AS ABREVIATURA, 
 6 AS CODCTABCOINT, 
 'SAFRA CD CONSUMIDOR' AS DESCRICAO,
 SUM(T3.VLRLANC * T3.RECDESP) as SALDO,
 CAST(max(t3.DHCONCILIACAO) as date) AS ULT_CONCILIACAO 
FROM TGFMBC T3 
WHERE T3.CODCTABCOINT =  6  AND T3.CONCILIADO =  'S' AND T3.DHCONCILIACAO  >= '01/01/2022' AND T3.DHCONCILIACAO  < getdate()


)Y