

SELECT DISTINCT CAB.NUNOTA, 
	CAB.CODVEND,
	VEN.APELIDO,
	CAB.CODUSUINC,
	USU.NOMEUSU, 
	CAB.CODPARC, 
	PAR.RAZAOSOCIAL, 
	PAR.NOMEPARC,
	PAR.CGC_CPF,
	CAB.VLRNOTA,
	(CAB.VLRNOTA - VLRIPI - VLRSUBST)TOT_PROD, 
	CAB.DTNEG,
	(SELECT TOP 1 NUMNOTA FROM TGFCAB INNER JOIN TGFVAR ON TGFVAR.NUNOTA = TGFCAB.NUNOTA WHERE TGFVAR.NUNOTAORIG = CAB.NUNOTA ) AS NFE,
	(CASE WHEN CAB.PENDENTE ='N' THEN 'SEM PENDECIA' ELSE 'PENDENTE'END) PENDENTE,
     (CASE WHEN LIB.EVENTO = 44 THEN '44-Cristiane' 
           WHEN LIB.EVENTO IN (1) THEN '1-José David' 
           WHEN LIB.EVENTO IN (2) THEN '2-José David'
           WHEN LIB.EVENTO IN (62) THEN '62-José David' 
           WHEN LIB.EVENTO IN (13) THEN '13-José David' 
		   ELSE '' END ) AS EVENTOS,
	CAB.APROVADO,
	CAB.CODTIPOPER,
	TOP1.DESCROPER,
	TPV.DESCRTIPVENDA,
	CAB.CODNAT,
	CAB.AD_DTAENTRADA_BW,
	CAB.AD_APROVLAYOUT,
	PAR.CODCID,
	CID.NOMECID, 
	UFS.UF, 
	CAB.STATUSNOTA,
	CAB.STATUSNFE,
	CAB.STATUSCTE,
	CAB.CODEMP
FROM TGFCAB CAB
	INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
	INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID
	INNER JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
	INNER JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC
	INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
	INNER JOIN TGFTOP TOP1 ON TOP1.CODTIPOPER = CAB.CODTIPOPER
	INNER JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
	INNER JOIN TGFTPV TPV ON TPV.CODTIPVENDA = CAB.CODTIPVENDA
WHERE CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
and CAB.TIPMOV = 'P'
AND CAB.CODNAT = 1010200
AND VEN.AD_SNCP_TELEVENDAS= 'S'
AND CAB.CODTIPOPER IN (1000,1240,1290,1246,1238)








